export interface FAQItem {
  id: string;
  category: 'General' | 'Quality & Testing' | 'Ordering & MOQ' | 'Shipping & Export' | 'Custom Formulations';
  question: string;
  answer: string;
}

export const FAQS_DATA: FAQItem[] = [
  {
    id: 'faq-1',
    category: 'General',
    question: 'Who is Mishari Phytolabs Private Limited?',
    answer: 'Mishari Phytolabs Private Limited is a premier Indian manufacturer and global exporter of standardized botanical extracts, herbal ingredients, nutraceutical raw materials, phytochemicals, essential oils, and customized plant-based solutions. We operate WHO-cGMP and ISO 9001 certified manufacturing facilities supplying pharmaceutical, nutraceutical, cosmetic, and food industries worldwide.'
  },
  {
    id: 'faq-2',
    category: 'Ordering & MOQ',
    question: 'What is your Minimum Order Quantity (MOQ)?',
    answer: 'Our standard Minimum Order Quantity (MOQ) for commercial production drums is 25 kg per item. For high-value custom extracts or initial R&D pilot trial batches, we offer flexible sample quantities starting from 1 kg to 5 kg upon request.'
  },
  {
    id: 'faq-3',
    category: 'Quality & Testing',
    question: 'Do you provide batch-specific Certificate of Analysis (COA) and MSDS?',
    answer: 'Yes! Every shipment is accompanied by a comprehensive batch-specific Certificate of Analysis (COA), Material Safety Data Sheet (MSDS), Technical Data Sheet (TDS), and HPLC/GC chromatogram reports generated by our ISO 17025 accredited quality laboratory.'
  },
  {
    id: 'faq-4',
    category: 'Shipping & Export',
    question: 'Which countries do you export to and what Incoterms do you support?',
    answer: 'We export directly to over 45 countries across North America, the European Union, the United Kingdom, Japan, South Korea, Australia, Latin America, and the Middle East. We support FOB (Freight on Board), CIF (Cost, Insurance & Freight), CFR, DDP (Delivered Duty Paid), and EXW terms via ocean container shipping or express air freight.'
  },
  {
    id: 'faq-5',
    category: 'Custom Formulations',
    question: 'Can you produce custom standardized extracts or private label formulations?',
    answer: 'Absolutely. Our in-house R&D team specializes in custom extraction ratios, targeted active marker percentages (e.g. 5% to 50%), organic solvent selection, custom mesh sizes, liposomal encapsulation, and private label OEM packaging tailored to your exact product specifications.'
  },
  {
    id: 'faq-6',
    category: 'Quality & Testing',
    question: 'Are your products tested for Ethylene Oxide (EtO), Heavy Metals, and Pesticides?',
    answer: 'Yes. All our products undergo 100% batch testing for heavy metals (Lead, Arsenic, Cadmium, Mercury via ICP-MS), residual solvents (via GC-HS), 400+ pesticide residues (via LC-MS/MS), and are guaranteed 100% Ethylene Oxide (EtO) free.'
  }
];
